version: '3'

services:

  backend:
    build: express-vuejs3-api
    environment:
      - CORS_FRONTEND_URL=http://127.0.0.1:8080 
    ports:
      - 3000:3000
    
  frontend:
    build: component_webapp
    environment:
      - VUE_APP_API_URL=http://172.19.0.3:3000
    ports:
      - 8080:8080
    depends_on:
      - backend